### ISSUE TITLE
Having sqlalchemy installed breaks freezegun

### ISSUE THREAD

**Issue by svenstaro** [spulec/freezegun#68]
So I get this:

`___________________ TestNotifications.test_conference_start ____________________
tests_python/api/test_notifications.py:20: in test_conference_start
    freez.start()
env/lib/python3.4/site-packages/freezegun/api.py:250: in start
    if attribute_value == real_datetime:
env/lib/python3.4/site-packages/sqlalchemy/orm/path_registry.py:54: in __eq__
    self.path == other.path
E   AttributeError: type object 'datetime.datetime' has no attribute 'path'`

Out of this code:

`freez = freeze_time("2017-01-14 12:00:00")
        freez.start()`

This worked in 0.2.2.
