### ISSUE TITLE
'dateutil.tz' module has no attribute 'UTC'

### ISSUE THREAD

**Issue by ToonoW** [spulec/freezegun#335]
I use the lastest version of freezegun==0.3.15

```python
# -*- coding: utf-8 -*-

from freezegun import freeze_time
freezer = freeze_time("2020-02-19 23:58:00")
freezer.start()


if __name__ == "__main__":
    from datetime import datetime
    print datetime.now()
    freezer.stop()

```

It's my code. It raise a exception.

```
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from freezegun import freeze_time
  File "/home/.local/lib/python2.7/site-packages/freezegun/__init__.py", line 9, in <module>
    from .api import freeze_time
  File "/home/.local/lib/python2.7/site-packages/freezegun/api.py", line 26, in <module>
    _EPOCHTZ = datetime.datetime(1970, 1, 1, tzinfo=dateutil.tz.UTC)
AttributeError: 'module' object has no attribute 'UTC'
```

And I check the file `dateutil/tz/__init__.py`, there is not found attribute 'UTC'.
```python
from .tz import *

__all__ = ["tzutc", "tzoffset", "tzlocal", "tzfile", "tzrange",
           "tzstr", "tzical", "tzwin", "tzwinlocal", "gettz"]
```

So, I think the lastest version `dateutil` not compare to lastest version `freezegun`.

And freezegun==0.3.14 is fine.

**Comment by millarm** [comment]
The issue is this?

https://github.com/dateutil/dateutil/issues/770

**Comment by millarm** [comment]
So the fix is simply to add

from dateutil import tz 

?

**Comment by spulec** [comment]
Closing as dupe of https://github.com/spulec/freezegun/issues/333

**Comment by sliwinski-milosz** [comment]
I think it is worth to mention that the latest version of freezegun that works fine with Python 2.7 is `freezegun==0.3.14`.
