### ISSUE TITLE
Failure with new Pandas 0.24.x: 'FakeDatetime' object has no attribute 'tz_localize'

### ISSUE THREAD

**Issue by MartinFalatic** [spulec/freezegun#284]
For a test using the following decorator:
`@freeze_time(pytz.timezone('America/Los_Angeles').localize(datetime(2017, 1, 1, 8, 0, 0)))`

Pandas 0.24.0 throws the following error:
```
pandas/_libs/tslibs/offsets.pyx:521: in pandas._libs.tslibs.offsets.BaseOffset.__radd__
    ???
pandas/_libs/tslibs/offsets.pyx:394: in pandas._libs.tslibs.offsets._BaseOffset.__add__
    ???
/usr/local/lib/python2.7/dist-packages/pandas/tseries/offsets.py:72: in wrapper
    result = conversion.localize_pydatetime(result, tz)
pandas/_libs/tslibs/conversion.pyx:595: in pandas._libs.tslibs.conversion.localize_pydatetime
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   AttributeError: 'FakeDatetime' object has no attribute 'tz_localize'

pandas/_libs/tslibs/conversion.pyx:612: AttributeError
```

There were a bunch of timezone-related updates to Pandas in this release:

https://pandas.pydata.org/pandas-docs/stable/whatsnew/v0.24.0.html

It appears that freezegun isn't (yet) providing the required attribute when creating a FakeDatetime object.

**Comment by MartinFalatic** [comment]
The issue continues when testing with Pandas 0.24.2.

**Comment by MartinFalatic** [comment]
As this may be a Pandas bug I've opened one with them with the following test code.

```
import pytz
import pandas
from datetime import datetime
from pandas.tseries.offsets import (CustomBusinessDay, BusinessDay)
from freezegun import freeze_time

LOCAL_TZ = pytz.timezone('America/Los_Angeles')

@freeze_time(LOCAL_TZ.localize(datetime(2019, 3, 15, 0, 0, 0)))
def these_work():
    pandas.Timestamp(datetime.now(LOCAL_TZ))
    pandas.Timestamp(datetime.now(LOCAL_TZ)) + BusinessDay(n=1)

@freeze_time(LOCAL_TZ.localize(datetime(2019, 3, 15, 0, 0, 0)))
def this_fails():
    pandas.Timestamp(datetime.now(LOCAL_TZ)) + CustomBusinessDay(n=1)

these_work()
this_fails()

```

**Comment by spulec** [comment]
It seems like they made a change with https://github.com/pandas-dev/pandas/pull/25853 that solves this. Feel free to reopen if I am reading wrong.

**Comment by MartinFalatic** [comment]
FYI to anyone coming here, this fix will likely never be backported to Pandas 0.24 (the last that works with Python 2.7).
